[tool.poetry]
name = "sftp-mounter"
version = "1.2.0"
description = "A simple Qt6 GUI tool to mount SFTP servers as network drives on Windows 11 using Rclone and WinFsp."
authors = ["turulomio <turulomio@yahoo.es>"]
readme = "README.md"
packages = [{include = "sftp_mounter"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
PySide6 = "^6.0.0"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.0.0"
poethepoet = "^0.24.0"
coverage = "^7.0.0"

[tool.poetry.scripts]
sftp-mounter = "sftp_mounter.main:main"

[tool.poe.tasks]
setup-wine-python = { script = "sftp_mounter.poethepoet:setup_wine_python" }
build-windows-wine = { script = "sftp_mounter.poethepoet:build_windows_wine" }
run-wine = { script = "sftp_mounter.poethepoet:run_wine" }
test = { script = "sftp_mounter.poethepoet:test" }
release = { script = "sftp_mounter.poethepoet:release" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "sftp_mounter/poethepoet.py",
    "*/poethepoet.py"
]
